# Generated by Django 3.1.12 on 2026-02-23 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_auto_20260223_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('user', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('user', 'email')},
        ),
    ]
